# Upptime configuration for BandLab Upptime Monitoring System
owner: bandlab
repo: bandlab-upptime
user-agent: BandLab-Upptime

# Monitoring targets
sites:
  - name: BandLab
    url: https://www.bandlab.com
    slug: bandlab
    maxResponseTime: 5000
    icon: https://www.bandlab.com/web-app/images/favicons/favicon-48x48-53ec365b4b.png
  - name: BandLab User Page
    url: https://www.bandlab.com/bandlab
    slug: bandlab-user-page
    maxResponseTime: 2000
    icon: https://www.bandlab.com/web-app/images/favicons/favicon-48x48-53ec365b4b.png

assignees:
  - ebashmakov

status-website:
  name: BandLab Status
  logoUrl: https://www.bandlab.com/web-app/images/favicons/favicon-48x48-53ec365b4b.png
  cname: upptime.bandlab.com
  introTitle: "**BandLab** availability monitoring"
  robotsText: "User-agent: * \n Disallow: /"
  theme: light
  navbar:
    - title: Status
      href: /
    - title: BandLab
      href: https://www.bandlab.com

# Workflow schedules (cron syntax)
# Note: GitHub Actions scheduled workflows cannot run faster than every 5 minutes
workflowSchedule:
  uptime: "*/5 * * * *"       # Check endpoint status every 5 minutes
  responseTime: "0 23 * * *"  # Record response times daily at 11 PM UTC
  staticSite: "0 1 * * *"     # Rebuild status website daily at 1 AM UTC
  graphs: "0 0 * * *"         # Generate response time graphs daily at midnight UTC
  summary: "0 0 * * *"        # Update README status summary daily at midnight UTC

notifications:
  slack:
    webhookUrl: ${{ secrets.SLACK_WEBHOOK_URL }}
