# Upptime configuration for BandLab Upptime Monitoring System
owner: bandlab
repo: bandlab-upptime
user-agent: bandlab

sites:
  - name: BandLab
    url: https://www.bandlab.com
    slug: bandlab
    maxResponseTime: 5000
    icon: https://www.bandlab.com/favicon.ico
  - name: BandLab Bandlab Page
    url: https://www.bandlab.com/bandlab
    slug: bandlab-page
    maxResponseTime: 2000
    icon: https://www.bandlab.com/web-app/images/favicons/favicon-48x48-53ec365b4b.png
  # - name: [Add more targets here]
  #   url: https://example.com
  #   slug: example
  #   maxResponseTime: 5000
  #   icon: https://example.com/favicon.ico

assignees:
  - ebashmakov
status-website:
  name: BandLab System Status
  logoUrl: https://www.bandlab.com/favicon.ico
  cname: upptime.bandlab.com
  introTitle: "**BandLab** system status and uptime monitoring"
  introMessage: Real-time monitoring of BandLab services powered by Upptime.
  theme: light
  navbar:
    - title: Status
      href: /
    - title: BandLab
      href: https://www.bandlab.com
    - title: GitHub
      href: https://github.com/bandlab/bandlab-upptime

# To further customize theme, logo, and intro text, see Upptime docs:
# https://upptime.js.org/docs/status-website/

workflowSchedule:
  uptime: "*/5 * * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"

# notifications:
#   slack:
#     webhookUrl: ${{ secrets.SLACK_WEBHOOK_URL }}
#   email:
#     to: team@bandlab.com
#     from: status@bandlab.com

